#!/usr/bin/env python3
"""
Convert .exr depth files from Blender rendering to disparity images.

This script processes the depth maps generated by blender_ego_rgb_depth.py
and converts them to disparity format suitable for training or visualization.

Usage:
    python exr_to_disparity.py --input_dir /path/to/depth/files --output_dir /path/to/output
    python exr_to_disparity.py --input_dir /path/to/depth/files --output_dir /path/to/output --batch_process
"""

import os
import argparse
import numpy as np
import imageio.v3 as iio
from pathlib import Path
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.cm as cmaps

# Add the training/aether/utils directory to the path to import postprocess_utils
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', 'training', 'aether', 'utils'))

try:
    from postprocess_utils import depth_to_disparity, colorize_depth
except ImportError:
    print("Warning: Could not import postprocess_utils. Using local implementation.")
    
    def depth_to_disparity(depth, sqrt_disparity=True):
        """Convert depth to disparity.
        
        Args:
            depth: (N, H, W) depth map
            sqrt_disparity (bool, optional): Whether to take the square root of the disparity.
                Defaults to True.
        Returns:
            (N, H, W) disparity map, dmax
        """
        import torch
        
        is_numpy = isinstance(depth, np.ndarray)
        if is_numpy:
            depth = torch.from_numpy(depth).float()
        
        disparity = 1.0 / depth
        valid_disparity = disparity[depth > 1e-6]
        dmax = valid_disparity.max()
        disparity = torch.clamp(disparity / dmax, min=0.0, max=1.0)

        if sqrt_disparity:
            disparity = torch.sqrt(disparity)

        if is_numpy:
            disparity = disparity.cpu().numpy()
        return disparity, dmax
    
    def colorize_depth(depth, cmap="Spectral"):
        """Colorize depth map for visualization."""
        min_d, max_d = (depth[depth > 0]).min(), (depth[depth > 0]).max()
        depth = (max_d - depth) / (max_d - min_d)

        cm = cmaps.get_cmap(cmap)
        depth = depth.clip(0, 1)
        depth = cm(depth, bytes=False)[..., 0:3]
        return depth


def load_exr_depth(file_path):
    """Load depth data from .exr file."""
    try:
        # Try using OpenEXR library first (more reliable for EXR files)
        try:
            import OpenEXR
            import Imath
            import array
            
            # Open the EXR file
            exr_file = OpenEXR.InputFile(str(file_path))
            
            # Get the data window
            dw = exr_file.header()['dataWindow']
            width = dw.max.x - dw.min.x + 1
            height = dw.max.y - dw.min.y + 1
            
            # Read the first channel (usually 'R' for depth)
            channels = exr_file.header()['channels'].keys()
            first_channel = list(channels)[0]
            
            # Read the channel data
            channel_data = exr_file.channel(first_channel, Imath.PixelType(Imath.PixelType.FLOAT))
            depth = np.frombuffer(channel_data, dtype=np.float32)
            depth = depth.reshape(height, width)
            
            exr_file.close()
            return depth
            
        except ImportError:
            # Fallback to imageio with OpenEXR support
            try:
                depth_data = iio.imread(file_path)
                
                # EXR files can have multiple channels, we want the first one for depth
                if depth_data.ndim == 3 and depth_data.shape[2] > 1:
                    # If it's a multi-channel EXR, take the first channel
                    depth = depth_data[:, :, 0]
                else:
                    depth = depth_data
                    
                return depth.astype(np.float32)
                
            except Exception as e2:
                print(f"imageio failed: {e2}")
                raise e2
    
    except Exception as e:
        print(f"Error loading {file_path}: {e}")
        print("Try installing OpenEXR support:")
        print("  pip install OpenEXR")
        print("  or")
        print("  conda install -c conda-forge openexr-python")
        return None


def process_single_file(input_path, output_dir, save_disparity_npy=True, save_colored_video=True, save_png=True, save_colored_png=False, fps=8):
    """Process a single .exr depth file."""
    # Load depth data
    depth = load_exr_depth(input_path)
    if depth is None:
        return False, None, None
    
    # Add small epsilon to avoid division by zero
    depth = depth + 1e-6
    
    # Convert depth to disparity
    disparity, dmax = depth_to_disparity(depth, sqrt_disparity=True)
    
    # Create output filename - extract frame number and create disparity_xxxx format
    input_name = Path(input_path).stem
    try:
        # Extract frame number from filename (assuming format like depth_0001.exr)
        frame_num = input_name.split('_')[-1]
        # Create disparity_xxxx format
        output_base = Path(output_dir) / f"disparity_{frame_num}"
    except (ValueError, IndexError):
        # Fallback to original format if we can't parse the frame number
        output_base = Path(output_dir) / f"{input_name}_disparity"
    
    # Save disparity as numpy array
    if save_disparity_npy:
        np.save(f"{output_base}.npy", disparity)
        print(f"Saved disparity: {output_base}.npy (dmax: {dmax:.6f})")
    
    # Save disparity as black/white PNG
    if save_png:
        # Convert disparity to 8-bit grayscale (0-255)
        disparity_8bit = (disparity * 255).astype(np.uint8)
        png_path = f"{output_base}.png"
        iio.imwrite(png_path, disparity_8bit)
        print(f"Saved B/W PNG: {png_path}")
    
    # Save colored disparity as PNG (optional)
    if save_colored_png:
        colored_disparity = colorize_depth(disparity)
        colored_png_path = f"{output_base}_colored.png"
        iio.imwrite(
            colored_png_path,
            (colored_disparity * 255).astype(np.uint8),
        )
        print(f"Saved colored PNG: {colored_png_path}")
    
    return True, disparity, dmax


def process_directory(input_dir, output_dir, save_disparity_npy=True, save_colored_video=True, save_png=True, save_colored_png=False, fps=8, start_frame=None, end_frame=None):
    """Process all .exr files in a directory and create a single video."""
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Find all .exr files and sort them
    exr_files = sorted(list(input_path.glob("*.exr")))
    
    if not exr_files:
        print(f"No .exr files found in {input_dir}")
        return
    
    # Apply frame range filtering
    if start_frame is not None or end_frame is not None:
        filtered_files = []
        for exr_file in exr_files:
            # Extract frame number from filename (assuming format like depth_0001.exr)
            try:
                frame_num = int(exr_file.stem.split('_')[-1])
                if start_frame is not None and frame_num < start_frame:
                    continue
                if end_frame is not None and frame_num > end_frame:
                    continue
                filtered_files.append(exr_file)
            except (ValueError, IndexError):
                # If we can't parse the frame number, include the file
                filtered_files.append(exr_file)
        exr_files = filtered_files
    
    print(f"Found {len(exr_files)} .exr files to process")
    if start_frame is not None or end_frame is not None:
        print(f"Frame range: {start_frame or 'start'} to {end_frame or 'end'}")
    
    # Process each file and collect disparities
    disparities = []
    dmax_values = []
    successful = 0
    
    for exr_file in tqdm(exr_files, desc="Processing depth files"):
        result = process_single_file(
            exr_file, 
            output_path, 
            save_disparity_npy, 
            False,  # Don't save individual videos
            save_png,
            save_colored_png,
            fps
        )
        
        if result[0]:  # If successful
            disparities.append(result[1])  # disparity
            dmax_values.append(result[2])  # dmax
            successful += 1
    
    # Create a single video from all frames
    if save_colored_video and disparities:
        try:
            # Stack all disparities
            disparity_sequence = np.stack(disparities, axis=0)
            
            # Colorize the entire sequence
            colored_sequence = colorize_depth(disparity_sequence)
            
            # Save as single video
            video_path = output_path / "disparity_sequence.mp4"
            iio.imwrite(
                str(video_path),
                (colored_sequence * 255).astype(np.uint8),
                fps=fps,
            )
            print(f"Saved sequence video: {video_path}")
            
            # Also save the full disparity sequence as numpy array
            sequence_path = output_path / "disparity_sequence.npy"
            np.save(str(sequence_path), disparity_sequence)
            print(f"Saved full sequence: {sequence_path}")
            
        except Exception as e:
            print(f"Error creating video: {e}")
            print("Try installing FFmpeg support: pip install 'imageio[ffmpeg]'")
    
    print(f"Successfully processed {successful}/{len(exr_files)} files")
    if dmax_values:
        print(f"Max disparity values range: {min(dmax_values):.6f} - {max(dmax_values):.6f}")


def batch_process_blender_output(base_dir, save_disparity_npy=True, save_colored_video=True, save_png=True, save_colored_png=False, fps=8, start_frame=None, end_frame=None):
    """Batch process the output from blender_ego_rgb_depth.py script."""
    base_path = Path(base_dir)
    
    # Look for the typical structure created by blender_ego_rgb_depth.py
    # base_dir/blend_filename/animation_name/depth/
    
    depth_dirs = []
    for blend_dir in base_path.iterdir():
        if blend_dir.is_dir():
            for anim_dir in blend_dir.iterdir():
                if anim_dir.is_dir():
                    depth_dir = anim_dir / "depth"
                    if depth_dir.exists():
                        depth_dirs.append(depth_dir)
    
    if not depth_dirs:
        print(f"No depth directories found in {base_dir}")
        print("Expected structure: base_dir/blend_filename/animation_name/depth/")
        return
    
    print(f"Found {len(depth_dirs)} depth directories to process")
    
    for depth_dir in tqdm(depth_dirs, desc="Processing depth directories"):
        # Create output directory structure
        output_dir = depth_dir.parent / "disparity"
        output_dir.mkdir(exist_ok=True)
        
        # Process all .exr files in this depth directory
        exr_files = list(depth_dir.glob("*.exr"))
        
        # Apply frame range filtering for batch processing
        if start_frame is not None or end_frame is not None:
            filtered_files = []
            for exr_file in exr_files:
                try:
                    frame_num = int(exr_file.stem.split('_')[-1])
                    if start_frame is not None and frame_num < start_frame:
                        continue
                    if end_frame is not None and frame_num > end_frame:
                        continue
                    filtered_files.append(exr_file)
                except (ValueError, IndexError):
                    filtered_files.append(exr_file)
            exr_files = filtered_files
        
        for exr_file in exr_files:
            process_single_file(
                exr_file,
                output_dir,
                save_disparity_npy,
                save_colored_video,
                save_png,
                save_colored_png,
                fps
            )


def main():
    parser = argparse.ArgumentParser(description="Convert .exr depth files to disparity images")
    parser.add_argument("--input_dir", type=str,
                       help="Input directory containing .exr depth files")
    parser.add_argument("--output_dir", type=str, required=True,
                       help="Output directory for disparity files")
    parser.add_argument("--batch_process", action="store_true",
                       help="Process the entire Blender output structure")
    parser.add_argument("--save_npy", action="store_true", default=False,
                       help="Save disparity as .npy files")
    parser.add_argument("--save_video", action="store_true", default=False,
                       help="Save colored disparity as video files")
    parser.add_argument("--save_png", action="store_true", default=True,
                       help="Save disparity as black/white PNG files for each frame")
    parser.add_argument("--save_colored_png", action="store_true", default=False,
                       help="Save colored disparity as PNG files for each frame")
    parser.add_argument("--fps", type=int, default=8,
                       help="FPS for output videos")
    parser.add_argument("--start_frame", type=int, default=None,
                       help="Start frame number (inclusive)")
    parser.add_argument("--end_frame", type=int, default=None,
                       help="End frame number (inclusive)")
    parser.add_argument("--single_file", type=str,
                       help="Process a single .exr file instead of directory")
    
    args = parser.parse_args()
    
    if args.single_file:
        # Process single file
        if not Path(args.single_file).exists():
            print(f"File not found: {args.single_file}")
            return
        
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        process_single_file(
            args.single_file,
            output_dir,
            args.save_npy,
            args.save_video,
            args.save_png,
            args.save_colored_png,
            args.fps
        )
    
    elif args.batch_process:
        # Process entire Blender output structure
        batch_process_blender_output(
            args.input_dir,
            args.save_npy,
            args.save_video,
            args.save_png,
            args.save_colored_png,
            args.fps,
            args.start_frame,
            args.end_frame
        )
    
    else:
        # Process directory
        process_directory(
            args.input_dir,
            args.output_dir,
            args.save_npy,
            args.save_video,
            args.save_png,
            args.save_colored_png,
            args.fps,
            args.start_frame,
            args.end_frame
        )


if __name__ == "__main__":
    main() 